### ISSUE TITLE
Doubt about the code

### ISSUE THREAD

**Issue by shikida** [CraftcodeCrew/Getting-Started-with-Telegrams-AbilityBot#1]
who calls this method?

    public Reply replyToButtons() {
        Consumer<Update> action = upd -> responseHandler.replyToButtons(getChatId(upd), upd.getCallbackQuery().getData());
        return Reply.of(action, Flag.CALLBACK_QUERY);
    }

**Comment by djuelg** [comment]
Yeah, I understand your confusion it's a little bit crazy what the AbilityBot library is doing there. Our "grandfather" class (BaseAbilityBot) is using reflection to find all public methods in the FitnessBot class that return either a Reply or an Ability. 

You can find the code here: https://github.com/rubenlagus/TelegramBots/blob/da5e7a776f01ae42f9154d6285d935a58d91c749/telegrambots-abilities/src/main/java/org/telegram/abilitybots/api/bot/BaseAbilityBot.java#L615
